version: "3"

services:
        # nginx:
        # image: nginx:latest
        # ports:
        # - '80:80'
        # volumes:
        #  - .:/app
        #  - ./nginx:/etc/nginx/conf.d
        #  - ./staticfiles:/static
        #  depends_on:
        #  - web
  web:
    image: porsche
    environment:
      SECRET_KEY: ${SECRET_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      M_DATABASE: ${M_DATABASE}
      M_USERNAME: ${M_USERNAME}
      M_PASSWORD: ${M_PASSWORD}
      M_HOSTNAME: ${M_HOSTNAME}
    command: ["chmod", "-R", "755", "./scripts", "&&", "./scripts/start_web.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"