version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - .:/app
      - ./nginx:/etc/nginx/conf.d
      - ./staticfiles:/static
    depends_on:
      - web
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"