on:
  push:
    branches:
      - master

name: Deploy to Amazon EC2
env:
  PROJECT_NAME: m
  BUCKET_NAME: mmoney

jobs:
  deploy:
    name: DEPLOY
    runs-on: ec2-user-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name mmoney --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name mmony-webservice-group --region ap-northeast-2 --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
